import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

import InitialPage from "@/components/InitialPage";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Accordion from "@/components/Accordion";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <InitialPage />
          </SignedOut>
          <SignedIn>
            <Header />
            {children}
            <Footer />
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
